"""
    Context: A counter is a container that stores elements as dictionary keys, and their counts are stored as dictionary values.
    Challenge: Get the total sales amount per day given a list of shoe sizes and a shopping list
    Summary:  Raghus a shoe shop owner. His shop has X number of shoes.
    He has a list containing the size of each shoe he has in his shop.
    There are N number of customers who are willing to pay xi amount of money only if they get the shoe of their desired size.

    Your task is to compute how much money Raghu earned.

    Input Format:
    - The first line contains X, the number of shoes.
    - The second line contains the space separated list of all the shoe sizes in the shop.
    - The third line contains N, the number of customers.
    - The next N lines contain the space separated values of the shoe size desired by the customer and xi, the price of the shoe.

    Output Format:
    Print the amount of money earned by Raghu.

    Sample Input:
    10 - Number of shoes in the shop
    2 3 4 5 6 8 7 6 5 18 - Shoe sizes
    6 - Customers
    6 55 - Customer 1
    6 45 - Customer 2
    6 55 - Customer 3
    4 40 - Customer 4
    18 60 - Customer 5
    10 50 - Customer 6

    Sample Output:
    200
"""
# This code was generated by ChatGPT and doesn't work
def get_sales_amount():
    shoe_amount = int(input().strip())
    shoe_sizes_input = input().split()
    shoe_sizes = [int(size) for size in shoe_sizes_input]

    customers = int(input())

    sales = [map(int, input().split()) for _ in range(customers)]

    amount = sum(quantity for size, quantity in sales if size in shoe_sizes)
    print(amount)

if __name__ == "__main__":
    get_sales_amount()
